stages:
  - setup
  - build
  - package
  - deploy

# prevent duplicate pipelines for merge request
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

variables:
  LINUX_RUSTIMG: "rust:buster"
  PKG_ROOT: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic"

.build-template:
  stage: build
  script:
    - cargo build ${FEATURES} ${CARGO_FLAGS}

.debian-build-template:
  extends:
    - .build-template
  image: ${LINUX_RUSTIMG}
  before_script:
    - apt-get update
    - apt-get install -y llvm-dev clang libxen-dev

.cross-build-template:
  extends:
    - .build-template
  image: ghcr.io/cross-rs/$CARGO_BUILD_TARGET:main
  before_script:
    # install Rust
    - curl --silent --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
    - . "$HOME/.cargo/env"
    - rustup target add $CARGO_BUILD_TARGET

.cross-freebsd12-x86_64-build-template:
  extends:
    - .cross-build-template
  variables:
    CARGO_BUILD_TARGET: "x86_64-unknown-freebsd"
    CROSS_SYSROOT: "/usr/local/x86_64-unknown-freebsd12"
  before_script:
    - !reference [.cross-build-template,before_script]
    # cross sysroot does not match its toolchain
    - mkdir -p $CROSS_SYSROOT/usr
    - ln -s ../include $CROSS_SYSROOT/usr/include
    - ln -s ../lib $CROSS_SYSROOT/usr/lib
    # build dependencies
    - PKG=$(./devscripts/freebsd-fetch-package.sh xen-tools)
    - tar -C $CROSS_SYSROOT/ --xform s,^/usr/local/,/usr/, -xf $PKG

.scheduled:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

.not-scheduled:
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"

## common defs

.featurematrix:
  parallel:
    matrix:
      - FEATURES:
          - ""
          - "--no-default-features"
          - "--no-default-features -F xenstore"
          - "--no-default-features -F net_netlink"
          - "--no-default-features -F net_pnet"

.featurematrix.no-netlink:
  parallel:
    matrix:
      - FEATURES:
          - "--no-default-features"
          - "--no-default-features -F xenstore"
          - "--no-default-features -F net_pnet"
          - "--no-default-features -F xenstore,net_pnet"

## standard jobs building with shipped Cargo.lock

env-setup:
  stage: setup
  image: alpine:latest
  before_script:
    - '[ "$CI_COMMIT_BRANCH" != "main" ] || apk add -y git'
  script:
    - |
      case "$CI_COMMIT_BRANCH" in
      main) UPSTREAMVERSION=$(git describe)
            TILDEVERSION=$UPSTREAMVERSION
            ;;
      *)    UPSTREAMVERSION=$(grep "^version =" Cargo.toml | cut -d\" -f2)
            # both DEB and RPM use "~" to sort pre-releases before releases
            TILDEVERSION=$(echo $UPSTREAMVERSION | tr "-" "~")
            ;;
      esac
    # update channel must be the same for matching packaging and deploy
    # jobs, set it once globally
    - |
      case "${CI_COMMIT_TAG}" in
      "") UPDATE_CHANNEL="${CI_COMMIT_REF_NAME}" ;;
      *-*) UPDATE_CHANNEL="testing" ;;
      *) UPDATE_CHANNEL="release" ;;
      esac

    - echo "UPDATE_CHANNEL=${UPDATE_CHANNEL}" > version.env
    - echo "UPSTREAMVERSION=${UPSTREAMVERSION}" >> version.env
    - echo "TILDEVERSION=${TILDEVERSION}" >> version.env

    - cat version.env

  artifacts:
    reports:
      # propagates variables into the pipeline level
      dotenv: version.env

build-linux-everycommit:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  parallel: !reference [.featurematrix,parallel]
  extends:
    - .debian-build-template
  variables:
    CARGO_FLAGS: "-v"
  before_script:
    - printf "\e[0Ksection_start:$(date +%s):before_script[collapsed=true]\r\e[0K\e[1;33mBuild setup\e[1;0m\n"
    - !reference [.debian-build-template,before_script]
    - printf "\e[0Ksection_end:$(date +%s):before_script\r\e[0K\n"
  script:
    # let git-rebase run the build for each commit, but not fail with
    # commit subject starts with "WIP" (gitlab also uses this string
    # to switch a PR back to draft, mitigating the risk to push a
    # failing commit)
    - git rebase --rebase-merges $CI_MERGE_REQUEST_DIFF_BASE_SHA
      --exec 'devscripts/gitlab-ci-runbuild.sh cargo build ${FEATURES} ${CARGO_FLAGS}'

build-linux:
  parallel: !reference [.featurematrix,parallel]
  extends:
    - .debian-build-template
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      # building branch tip already included in 'everycommit'
      when: never
    - !reference [.not-scheduled,rules]
  variables:
    CARGO_FLAGS: "-v"

build-release-linux-x86_64:
  extends:
    - .debian-build-template
    - .not-scheduled
  variables:
    FEATURES: ""
    CARGO_FLAGS: "--release"
  artifacts:
    paths:
      - target/release/xen-guest-agent

build-freebsd12-x86_64:
  extends:
    - .cross-freebsd12-x86_64-build-template
    - .not-scheduled
  variables:
    CARGO_FLAGS: "-v"
  parallel: !reference [.featurematrix.no-netlink,parallel]

build-release-freebsd12-x86_64:
  extends:
    - .cross-freebsd12-x86_64-build-template
    - .not-scheduled
  variables:
    FEATURES: "--no-default-features -F xenstore,net_pnet"
    CARGO_FLAGS: "--release"
  artifacts:
    paths:
      - target/x86_64-unknown-freebsd/release/xen-guest-agent

## continuous checking against most recent dependencies

build-latest-linux:
  parallel: !reference [.featurematrix,parallel]
  extends:
    - .debian-build-template
    - .scheduled
  before_script:
    - !reference [".debian-build-template", "before_script"]
    - mv Cargo.lock Cargo.lock.current
  after_script:
    # show which dependencies changed in Cargo.lock
    - git diff

## source packaging

pkg-source:
  stage: package
  image: ${LINUX_RUSTIMG}
  script:
    - cargo package --no-verify
    - CRATEFILE=$(basename target/package/xen-guest-agent-*.crate)
    - mv target/package/${CRATEFILE} target/package/${CRATEFILE%.crate}.tar.gz
  artifacts:
    paths:
      - target/package/*.tar.gz

## packaging from binary artifacts

pkg-deb-amd64:
  stage: package
  image: "debian:10"
  extends:
    - .not-scheduled
  needs:
    - env-setup
    - build-release-linux-x86_64
  before_script:
    - apt update
    - apt install -y build-essential debhelper apt-utils
    - dpkg-checkbuilddeps
  script:
    - >-
      sed < debian/changelog.in > debian/changelog
      -e "s/@@VERSION@@/$TILDEVERSION/"
      -e "s/@@AUTHOR@@/$GITLAB_USER_NAME <$GITLAB_USER_EMAIL>/"
      -e "s/@@DATE@@/$(date --rfc-822)/"
    - fakeroot debian/rules binary AGENT_BINARY="target/release/xen-guest-agent"
    - mv -v ../*.deb target/release/

    # repository metadata
    - cd target/release

    # mangle names to avoid chars rejected by the gitlab package registry,
    # see https://gitlab.com/gitlab-org/gitlab/-/issues/413517
    - for FILE in *.deb; do mv $FILE $(echo $FILE | tr "~" "-"); done

    - apt-ftparchive generate ../../apt-ftparchive.conf

    # post-processing so we can use `deb https://...generic/deb-amd64/ main/`
    - 'sed -i "s,^Filename: ./,Filename: ${UPDATE_CHANNEL}/," Packages'

    - apt-ftparchive release .
      -o APT::FTPArchive::Release::Description="xen-guest-agent CI packages for ${UPDATE_CHANNEL}"
      -o APT::FTPArchive::Release::Label="xen-guest-agent-ci"
      -o APT::FTPArchive::Release::Suite="${UPDATE_CHANNEL}"
      > Release.part
    - mv Release.part Release
  artifacts:
    paths:
      - target/release/*.deb
      - target/release/*Release*
      - target/release/Packages*
      - target/release/Contents-*

# The artifact repo does not seem to work well as an APT source, APT
# gets HTP 400 on Packages for some reason, so deploy it to a package
# repository instead.
deploy-deb-amd64:
  stage: deploy
  needs:
    - env-setup
    - pkg-deb-amd64
  image: "curlimages/curl:latest"
  script:
    - cd target/release
    - for FILE in *; do
    -   echo "uploading '$FILE'"
    -   >
        curl --silent --header "JOB-TOKEN: $CI_JOB_TOKEN"
        --upload-file "$FILE"
        "${PKG_ROOT}/deb-amd64/${UPDATE_CHANNEL}/${FILE}"
    - done

pkg-rpm-x86_64:
  stage: package
  image: "fedora:37"
  extends:
    - .not-scheduled
  needs:
    - env-setup
    - build-release-linux-x86_64
  before_script:
    - dnf install -y rpm-build dnf-utils
    - mkdir SOURCES
    - ln -sr target/release/xen-guest-agent SOURCES/
    - ln -sr startup/xen-guest-agent.service SOURCES/
    - >-
      sed  < xen-guest-agent.spec.in > xen-guest-agent.spec
      -e "s/@@UPSTREAMVERSION@@/$UPSTREAMVERSION/"
      -e "s/@@VERSION@@/$TILDEVERSION/"
      -e "s/@@AUTHOR@@/$GITLAB_USER_NAME <$GITLAB_USER_EMAIL>/"
      -e "s/@@DATE@@/$(date +'%a %b %d %Y')/"
    - dnf builddep xen-guest-agent.spec -y
  script:
    - 'rpmbuild -bb xen-guest-agent.spec --define "_topdir $(pwd)"'
  artifacts:
    paths:
      - RPMS/*/*.rpm
