[package]
name = "xen-guest-agent"
version = "0.1.0"
authors = ["Yann Dirson <yann.dirson@vates.fr>"]
edition = "2018"
#rust-version = "1.67"

[dependencies]
uname = "0.1.1"
xenstore-rs = { version = "0.3.2", optional = true }

[features]
default = ["xenstore"]
xenstore = ["dep:xenstore-rs"]

[patch.crates-io]
xenstore-rs = { git = "https://github.com/xcp-ng/xenstore-rs.git", branch = "xs_write" }
