[patch.crates-io.libc]
git = "https://github.com/xcp-ng/rust-libc.git"
#branch = "freebsd-netlink-0.2"
# cannot specify a cargo feature here, so use a version exposing
# freebsd-netlink support without needing a feature
rev = "bfe4c69a83a9e6fc4fe92867c7ebbc471b723ccb"
